### ISSUE TITLE
[BUG] Some show statuses show up as undefined

### ISSUE THREAD

**Issue by filiptrplan** [rivenmedia/riven-frontend#105]
**Describe the bug**
Some show statuses show up as undefined

**To Reproduce**
Not quite sure what causes it, they are mostly shows that are airing but don't have all the episodes downloaded yet.

**Expected behavior**
Should be something like "airing" or "in progress"

**Screenshots**
![image](https://github.com/user-attachments/assets/086aeb72-3cd6-4c41-a1f0-7ef854eb5047)
![image](https://github.com/user-attachments/assets/bb465446-ed6b-406e-be0e-c6c14a372f15)

**Comment by dreulavelle** [comment]
its normal.. backend added 2 new states, which aren't yet in the frontend. Mini is on vacation right now and will update soon
