### ISSUE TITLE
[Feature request] Add websocket support for updating the item states

### ISSUE THREAD

**Issue by filiptrplan** [rivenmedia/riven-frontend#113]
We could make the website more reactive and leverage websockets to listen for events and refresh the pages when the state of items changes.

**Comment by dreulavelle** [comment]
I see this being rather annoying with the constant refreshes?

**Comment by filiptrplan** [comment]
> I see this being rather annoying with the constant refreshes?

SvelteKit can invalidate the data provided by the server and refetch the updated data without actually refreshing the page. I just used the word "refresh", "refetch" would be more appropriate

**Comment by AyushSehrawat** [comment]
> We could make the website more reactive and leverage websockets to listen for events and refresh the pages when the state of items changes.

Current websockets implementation kinda sucks, i am converting websockets to sse (server side events). We can just have some api call every x second to see if new data 🤔
