### ISSUE TITLE
Frontend config in standalone folder

### ISSUE THREAD

**Issue by arrrrrrrrrrrrrrrrrr** [rivenmedia/riven-frontend#161]
putting server-config.json into a standalone folder, will be easier to bind to local directory, so users won't need type in api and backend url everytime they update.

**Comment by davidemarcoli** [comment]
Why do we need a separate directory? You could also define a mount which targets only this single file.

**Comment by arrrrrrrrrrrrrrrrrr** [comment]
if we target a single file, then the file should already be existed in the targeted folder, but if we do a folder, then it will create the file when the container started.
