### ISSUE TITLE
[BUG] Filters don't work on Safari

### ISSUE THREAD

**Issue by ronaldland** [rivenmedia/riven-frontend#177]
**Describe the bug**
Selecting/deselecting filters does not work on Safari macOS and iOS. Clicking a filter in the dropdown does not change the state.
Here is a log from the console where I try to change the state filter on the browse page:
TypeError: selectedStates.values().map is not a function. (In 'selectedStates.values().map((v) => v.value)', 'selectedStates.values().map' is undefined)

It works on Firefox and Chrome for macOS.

**To Reproduce**
1. Go to /browse on Safari browser
2. Click on state filter
3. Select/deselect a filter value

**Expected behavior**
A filter where the filter values can change

- OS: macOS and iOS 
- Browser: Safari
- Version: 18.1

**Comment by davidemarcoli** [comment]
@ronaldland This is fixed with your pr, right? Can this issue be closed?
