### ISSUE TITLE
[Feature Request] Remember my filters on the library screen

### ISSUE THREAD

**Issue by IczerX01** [rivenmedia/riven-frontend#88]
When I set filters on the library screen and then navigate away and come back the filters are reset. This is an inconvenience when diving into a movie/show and then coming back to the library.

**Comment by AyushSehrawat** [comment]
Navigating back and forth should make it go to the previous/next url and filters should work since i use url query (?abc=x) for filtering

**Comment by IczerX01** [comment]
Ahh I see. I guess I don't use the browser back. I was just clicking the library link again.

**Comment by IczerX01** [comment]
I'll close this then since there is a solution.
